plugins { id 'java' }

repositories {
    maven { url 'https://jitpack.io' }
    mavenCentral()
}

dependencies {
    compileOnly 'com.github.Anuken.Arc:arc-core:v158'
    compileOnly 'com.github.Anuken.Mindustry:core:v158'
}

jar {
    from configurations.runtimeClasspath.collect {
        it.isDirectory() ? it : zipTree(it)
    }
}